package com.rochcap.cpa.tags;

import java.util.LinkedHashMap;


public class Countrys {

	
	public LinkedHashMap<String, String> getCountrys()
	{
		LinkedHashMap<String, String> country = new LinkedHashMap<String, String>();
		country.put("AF", "AFGHANISTAN");
		country.put("AX", "ALAND ISLANDS");
		country.put("AL", "ALBANIA");
		country.put("DZ", "ALGERIA");
		country.put("AS", "AMERICAN SAMOA");
		country.put("AD", "ANDORRA");
		country.put("AO", "ANGOLA");
		country.put("AI", "ANGUILLA");
		country.put("AQ", "ANTARCTICA");
		country.put("AG", "ANTIGUA AND BARBUDA");
		country.put("AR", "ARGENTINA");
		country.put("AM", "ARMENIA");
		country.put("AW", "ARUBA");
		country.put("AU", "AUSTRALIA");
		country.put("AT", "AUSTRIA");
		country.put("AZ", "AZERBAIJAN");
		country.put("BS", "BAHAMAS");
		country.put("BH", "BAHRAIN");
		country.put("BD", "BANGLADESH");
		country.put("BB", "BARBADOS");
		country.put("BY", "BELARUS");
		country.put("BE", "BELGIUM");
		country.put("BZ", "BELIZE");
		country.put("BJ", "BENIN");
		country.put("BM", "BERMUDA");
		country.put("BT", "BHUTAN");
		country.put("BO", "BOLIVIA, PLURINATIONAL STATE OF");
		country.put("BQ", "BONAIRE, SINT EUSTATIUS AND SABA");
		country.put("BA", "BOSNIA AND HERZEGOVINA");
		country.put("BW", "BOTSWANA");
		country.put("BV", "BOUVET ISLAND");
		country.put("BR", "BRAZIL");
		country.put("IO", "BRITISH INDIAN OCEAN TERRITORY");
		country.put("BN", "BRUNEI DARUSSALAM");
		country.put("BG", "BULGARIA");
		country.put("BF", "BURKINA FASO");
		country.put("BI", "BURUNDI");
		country.put("KH", "CAMBODIA");
		country.put("CM", "CAMEROON");
		country.put("CA", "CANADA");
		country.put("CV", "CAPE VERDE");
		country.put("KY", "CAYMAN ISLANDS");
		country.put("CF", "CENTRAL AFRICAN REPUBLIC");
		country.put("TD", "CHAD");
		country.put("CL", "CHILE");
		country.put("CN", "CHINA");
		country.put("CX", "CHRISTMAS ISLAND");
		country.put("CC", "COCOS (KEELING) ISLANDS");
		country.put("CO", "COLOMBIA");
		country.put("KM", "COMOROS");
		country.put("CD", "CONGO");
		country.put("CG", "CONGO, DEMOCRATIC REPUBLIC OF THE");
		country.put("CK", "COOK ISLANDS");
		country.put("CR", "COSTA RICA");
		country.put("CI", "CÔTE D'IVOIRE");
		country.put("HR", "CROATIA");
		country.put("CU", "CUBA");
		country.put("CW", "CURAÇAO");
		country.put("CY", "CYPRUS");
		country.put("CZ", "CZECH REPUBLIC");
		country.put("DK", "DENMARK");
		country.put("DJ", "DJIBOUTI");
		country.put("DM", "DOMINICA");
		country.put("DO", "DOMINICAN REPUBLIC");
		country.put("EC", "ECUADOR");
		country.put("EG", "EGYPT");
		country.put("SV", "EL SALVADOR");
		country.put("GQ", "EQUATORIAL GUINEA");
		country.put("ER", "ERITREA");
		country.put("EE", "ESTONIA");
		country.put("ET", "ETHIOPIA");
		country.put("FK", "FALKLAND ISLANDS (MALVINAS)");
		country.put("FO", "FAROE ISLANDS");
		country.put("FJ", "FIJI");
		country.put("FI", "FINLAND");
		country.put("FR", "FRANCE");
		country.put("GF", "FRENCH GUIANA");
		country.put("PF", "FRENCH POLYNESIA");
		country.put("TF", "FRENCH SOUTHERN TERRITORIES");
		country.put("GA", "GABON");
		country.put("GM", "GAMBIA");
		country.put("GE", "GEORGIA");
		country.put("DE", "GERMANY");
		country.put("GH", "GHANA");
		country.put("GI", "GIBRALTAR");
		country.put("GR", "GREECE");
		country.put("GL", "GREENLAND");
		country.put("GD", "GRENADA");
		country.put("GP", "GUADELOUPE");
		country.put("GU", "GUAM");
		country.put("GT", "GUATEMALA");
		country.put("GG", "GUERNSEY");
		country.put("GN", "GUINEA");
		country.put("GW", "GUINEA-BISSAU");
		country.put("GY", "GUYANA");
		country.put("HT", "HAITI");
		country.put("HM", "HEARD ISLAND AND MCDONALD ISLANDS");
		country.put("HN", "HONDURAS");
		country.put("HK", "HONG KONG");
		country.put("HU", "HUNGARY");
		country.put("IS", "ICELAND");
		country.put("IN", "INDIA");
		country.put("ID", "INDONESIA");
		country.put("IR", "IRAN, ISLAMIC REPUBLIC OF");
		country.put("IQ", "IRAQ");
		country.put("IE", "IRELAND");
		country.put("IM", "ISLE OF MAN");
		country.put("IL", "ISRAEL");
		country.put("IT", "ITALY");
		country.put("JM", "JAMAICA");
		country.put("JP", "JAPAN");
		country.put("JE", "JERSEY");
		country.put("JO", "JORDAN");
		country.put("KZ", "KAZAKHSTAN");
		country.put("KE", "KENYA");
		country.put("KI", "KIRIBATI");
		country.put("KP", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF");
		country.put("KR", "KOREA, REPUBLIC OF");
		country.put("KW", "KUWAIT");
		country.put("KG", "KYRGYZSTAN");
		country.put("LA", "LAO PEOPLE'S DEMOCRATIC REPUBLIC");
		country.put("LV", "LATVIA");
		country.put("LB", "LEBANON");
		country.put("LS", "LESOTHO");
		country.put("LR", "LIBERIA");
		country.put("LY", "LIBYA");
		country.put("LI", "LIECHTENSTEIN");
		country.put("LT", "LITHUANIA");
		country.put("LU", "LUXEMBOURG");
		country.put("MO", "MACAO");
		country.put("MK", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF");
		country.put("MG", "MADAGASCAR");
		country.put("MW", "MALAWI");
		country.put("MY", "MALAYSIA");
		country.put("MV", "MALDIVES");
		country.put("ML", "MALI");
		country.put("MT", "MALTA");
		country.put("MH", "MARSHALL ISLANDS");
		country.put("MQ", "MARTINIQUE");
		country.put("MR", "MAURITANIA");
		country.put("MU", "MAURITIUS");
		country.put("YT", "MAYOTTE");
		country.put("MX", "MEXICO");
		country.put("FM", "MICRONESIA, FEDERATED STATES OF");
		country.put("MD", "MOLDOVA, REPUBLIC OF");
		country.put("MC", "MONACO");
		country.put("MN", "MONGOLIA");
		country.put("ME", "MONTENEGRO");
		country.put("MS", "MONTSERRAT");
		country.put("MA", "MOROCCO");
		country.put("MZ", "MOZAMBIQUE");
		country.put("MM", "MYANMAR");
		country.put("NA", "NAMIBIA");
		country.put("NR", "NAURU");
		country.put("NP", "NEPAL");
		country.put("NL", "NETHERLANDS");
		country.put("NC", "NEW CALEDONIA");
		country.put("NZ", "NEW ZEALAND");
		country.put("NI", "NICARAGUA");
		country.put("NE", "NIGER");
		country.put("NG", "NIGERIA");
		country.put("NU", "NIUE");
		country.put("NF", "NORFOLK ISLAND");
		country.put("MP", "NORTHERN MARIANA ISLANDS");
		country.put("NO", "NORWAY");
		country.put("OM", "OMAN");
		country.put("PK", "PAKISTAN");
		country.put("PW", "PALAU");
		country.put("PS", "PALESTINIAN TERRITORY, OCCUPIED");
		country.put("PA", "PANAMA");
		country.put("PG", "PAPUA NEW GUINEA");
		country.put("PY", "PARAGUAY");
		country.put("PE", "PERU");
		country.put("PH", "PHILIPPINES");
		country.put("PN", "PITCAIRN");
		country.put("PL", "POLAND");
		country.put("PT", "PORTUGAL");
		country.put("PR", "PUERTO RICO");
		country.put("QA", "QATAR");
		country.put("RE", "RÉUNION");
		country.put("RO", "ROMANIA");
		country.put("RU", "RUSSIAN FEDERATION");
		country.put("RW", "RWANDA");
		country.put("BL", "SAINT BARTHÉLEMY");
		country.put("SH", "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA");
		country.put("KN", "SAINT KITTS AND NEVIS");
		country.put("LC", "SAINT LUCIA");
		country.put("MF", "SAINT MARTIN (FRENCH PART)");
		country.put("PM", "SAINT PIERRE AND MIQUELON");
		country.put("VC", "SAINT VINCENT AND THE GRENADINES");
		country.put("WS", "SAMOA");
		country.put("SM", "SAN MARINO");
		country.put("ST", "SAO TOME AND PRINCIPE");
		country.put("SA", "SAUDI ARABIA");
		country.put("SN", "SENEGAL");
		country.put("RS", "SERBIA");
		country.put("SC", "SEYCHELLES");
		country.put("SL", "SIERRA LEONE");
		country.put("SG", "SINGAPORE");
		country.put("SX", "SINT MAARTEN (DUTCH PART)");
		country.put("SK", "SLOVAKIA");
		country.put("SI", "SLOVENIA");
		country.put("SB", "SOLOMON ISLANDS");
		country.put("SO", "SOMALIA");
		country.put("ZA", "SOUTH AFRICA");
		country.put("GS", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS");
		country.put("SS", "SOUTH SUDAN");
		country.put("ES", "SPAIN");
		country.put("LK", "SRI LANKA");
		country.put("SD", "SUDAN");
		country.put("SR", "SURINAME");
		country.put("SJ", "SVALBARD AND JAN MAYEN");
		country.put("SZ", "SWAZILAND");
		country.put("SE", "SWEDEN");
		country.put("CH", "SWITZERLAND");
		country.put("SY", "SYRIAN ARAB REPUBLIC");
		country.put("TW", "TAIWAN, PROVINCE OF CHINA");
		country.put("TJ", "TAJIKISTAN");
		country.put("TZ", "TANZANIA, UNITED REPUBLIC OF");
		country.put("TH", "THAILAND");
		country.put("TL", "TIMOR-LESTE");
		country.put("TG", "TOGO");
		country.put("TK", "TOKELAU");
		country.put("TO", "TONGA");
		country.put("TT", "TRINIDAD AND TOBAGO");
		country.put("TN", "TUNISIA");
		country.put("TR", "TURKEY");
		country.put("TM", "TURKMENISTAN");
		country.put("TC", "TURKS AND CAICOS ISLANDS");
		country.put("TV", "TUVALU");
		country.put("UG", "UGANDA");
		country.put("UA", "UKRAINE");
		country.put("AE", "UNITED ARAB EMIRATES");
		country.put("GB", "UNITED KINGDOM");
		country.put("UM", "UNITED STATES MINOR OUTLYING ISLANDS");
		country.put("UY", "URUGUAY");
		country.put("UZ", "UZBEKISTAN");
		country.put("VU", "VANUATU");
		country.put("VA", "VATICAN CITY (HOLY SEE)");		
		country.put("VE", "VENEZUELA, BOLIVARIAN REPUBLIC OF");
		country.put("VN", "VIETNAM");
		country.put("VG", "VIRGIN ISLANDS, BRITISH");
		country.put("VI", "VIRGIN ISLANDS, U.S.");
		country.put("WF", "WALLIS AND FUTUNA");
		country.put("EH", "WESTERN SAHARA");
		country.put("YE", "YEMEN");
		country.put("ZM", "ZAMBIA");
		country.put("ZW", "ZIMBABWE");
			
		
		return country;
	}
}
